name: 'Compute - VirtualMachineScaleSets'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.compute.virtualmachinescalesets.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.Compute/virtualMachineScaleSets/*'
      - '/modules/.global/global.module.tests.ps1'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/dependencies/*'
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.Compute/virtualMachineScaleSets'

stages:
  - stage: Validation
    displayName: Static validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: Deployment
    displayName: Deployment validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.test/linux.min.parameters.json
            - path: $(modulePath)/.test/linux.parameters.json
            - path: $(modulePath)/.test/windows.min.parameters.json
            - path: $(modulePath)/.test/windows.parameters.json

  - stage: Publishing
    displayName: Publishing
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.prerelease }}', 'true')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
