name: '.Platform: Auto Assign PR'
on:
  pull_request:
    types: [opened]

jobs:
  autoassign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/platform.auto-assign-PR.configuration.yml'
